[project]
name = "jp-qcew"
version = "1.1.0"
authors = [{ name = "Alejandro Ousland", email = "alejandro.ouslan@upr.edu" }]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "duckdb>=1.1.3",
  "fastexcel>=0.12.1",
  "ibis-framework[duckdb]>=9.5.0",
  "pandas>=2.2.3",
  "polars>=1.17.1",
  "requests>=2.32.3",
  "tqdm>=4.67.1",
]

[dependency-groups]
dev = ["jupyter>=1.1.1", "matplotlib>=3.10.0", "pynvim>=0.5.2"]
