[project]
name = "jp-qcew"
version = "0.1.0"
authors = [{ name = "Alejandro Ousland", email = "alejandro.ouslan@upr.edu" }]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ibis-framework[sqlite]>=9.5.0",
    "pandas>=2.2.3",
    "polars>=1.17.1",
    "psycopg2-binary>=2.9.10",
    "sqlmodel>=0.0.22",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
